---
title: "Article 3 :Scientists warn a million species at risk of extinction"
description: 
 
author:
  - name: Samuel Marcelli
    url: {}
date: 11-17-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT:

Source of the article: https://www.reuters.com/article/us-un-environment-biodiversity/scientists-warn-a-million-species-at-risk-of-extinction-idUSKCN1SC0PJ

Word count: 628

### VOCABULARY: 

| Word from the text | Synonym/definition in English                                                                                                                                 | French Translation                   |
| ------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------ |
| humankind          | human beings considered collectively (used as a neutral alternative to “mankind”).                                                                            | humanité                             |
| relentless         | oppressively constant; incessant.                                                                                                                             | incessant                            |
| vested             | secured in the possession of or assigned to a person                                                                                                          | acquis                               |
| chaired            | to direct the running of (a meeting, etc.);act as chairperson of                                                                                              | présidé                              |
| gesture            | a movement or position of the hand, arm, body, head, or face that expresses an idea, opinion, emotion, etc                                                    | sens dans le texte: geste de la main |
| long-lasting       | enduring or existing for a long period of time                                                                                                                | durable                              |
| undertaken         | to take upon oneself, as a task or performance;attempt                                                                                                        | entrepris                            |
| fates              | something that unavoidably happens to a person;one's fortune or lot                                                                                           | destin                               |
| embrace            | to accept or adopt willingly                                                                                                                                  | accepter (une idée)                  |
| upsurge            | to surge up;increase;rise.                                                                                                                                    | augmentation                         |
| blunt              | abrupt in manner, without politeness:                                                                                                                         | direct ( sans politesse)             |
| curb               | anything that restrains or controls;restraint;check:                                                                                                          | freiner ( la progression de qqch)    |
| greenhouse gases   | any of the gases that absorb energy from the sun and so contribute to the greenhouse effect, including carbon dioxide, methane, ozone, and the fluorocarbons. | gaz à effet de serre                 |

### ANALYSIS TABLE ABOUT THE STUDY:

| Researchers?                       | Writing by Matthew Green; Editing by Frances Kerry and Gareth Jones                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| ---------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Published in? when (if mentioned)? | Sustainable business; May 6 2019                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|  General topic                     | One million animal and plant species are at imminent risk of extinction due to humankind’s relentless pursuit of economic growth.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| Procedure/ what was examined       | Climate change and business like industrial farming and fishing are the major causes of the crisis of animal extinction, the current rate of species extinction tens to hundreds of times higher than the average over the last 10 million years.The report identified a range of risks, from the disappearance of insects vital for pollinating food crops, to the destruction of coral reefs that support fish populations and the loss of medicinal plants.The threatened list includes more than 40 percent of amphibian species, almost 33 percent of reef-forming corals, sharks and shark relatives, and more than a third of all marine mammals. |
| Conclusions/ discovery             | “We have reconfigured dramatically the life of the planet,”, we must have economic and social laws to curb greenhouse gases and global warming, and also laws to protect wildlife and threatened animals to avoid extinction                                                                                                                                                                                                                                                                                                                                                                                                                             |
| Remaining questions                | /                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
